### ISSUE TITLE
I would like to choose my own object name

### ISSUE THREAD

**Issue by avandalen** [ElectricRCAircraftGuy/eRCaGuy_Timer2_Counter#13]
I would like to choose my own object name, such as
`eRCaGuy_Timer2_Counter timer_us_x2;`
This name clearly indicates what it does
Can you make that possible?

**Comment by edgar-bonet** [comment]
You may define a reference to the object, and use it as an “alias”:

```c++
eRCaGuy_Timer2_Counter &timer_us_x2 = timer2;
```

**Comment by avandalen** [comment]
thanks!

**Comment by ElectricRCAircraftGuy** [comment]
## C-style macro

You can also use a macro. It is recommended, by convention, to capitalize macros though, so it might look like this:

```cpp
#define TIMER_US_X2 timer2
```

Then you just use `TIMER_US_X2` in your code wherever `timer2` was used before:
```cpp
TIMER_US_X2.setup();
// etc.
```


## C++ reference

The reference approach by @edgar-bonet is also an excellent approach:
```cpp
eRCaGuy_Timer2_Counter &timer_us_x2 = timer2;

// then use it like this:
timer_us_x2.setup();
```


## C-style pointer

Lastly, you can use a pointer. But, for pointers, you must replace the `.` operator with `->` instead:
```cpp
eRCaGuy_Timer2_Counter* timer_us_x2 = &timer2;

// then use it like this:
timer_us_x2->setup();
// etc.
```

**Comment by ElectricRCAircraftGuy** [comment]
Closing since there are already 3 ways to do this:
1. C++ reference
2. C-style macro
3. C-style pointer

More comments are welcome.
