### ISSUE TITLE
Adaptive RC Sailing

### ISSUE THREAD

**Issue by adaptivercsailing** [ElectricRCAircraftGuy/eRCaGuy_Timer2_Counter#9]
Gabriel,

Please check [your hobbyist email listed here](https://www.electricrcaircraftguy.com/2013/01/contact-me.html).
and please visit https://github.com/adaptivercsailing/adaptivercsailing and
www.adaptivercsailer.com

Dave K

**Comment by ElectricRCAircraftGuy** [comment]
Done. As far as I can tell, from our several phone discussions and video meetings, you now have this totally working in your Phase 2 part of the project. Example where you are using my PPM writer library: https://github.com/adaptivercsailing/adaptivercsailing/blob/main/Phase_2/arduino_src/Adaptive_RC_Sailer_PPM_FlySkyi6X.ino. 


....and you don't need the TimerCounter library directly for what you're trying to do. Closing this issue.
